version: '3'
services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
#    volumes:
#      - /Users/lsun/PycharmProjects/rabbitmq-tutorial/data/:/var/lib/rabbitmq/
#      - /Users/lsun/PycharmProjects/rabbitmq-tutorial/log/:/var/log/rabbitmq/

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

networks:
  rasa-network:
    driver: bridge